[player]
health = 3000

[[player.cards]]
name = "Sapphire"
tier = "Silver"

[[player.cards]]
name = "Abacus"
tier = "Gold"

[[player.cards]]
name = "Trained Spider"
tier = "Bronze"

[[player.cards]]
name = "Trained Spider"
tier = "Diamond"

[[player.cards]]
name = "Trained Spider"
tier = "Bronze"

[[player.cards]]
name = "Trained Spider"
tier = "Bronze"

[[player.cards]]
name = "Trained Spider"
tier = "Bronze"

[opponent]
health = 3000

[[opponent.cards]]
name = "Lighter"
tier = "Bronze"

[[opponent.cards]]
name = "Lighter"
tier = "Bronze"

[[opponent.cards]]
name = "Lighter"
tier = "Bronze"

[[player.cards]]
name = "Abacus"
tier = "Gold"

[[opponent.cards]]
name = "Fang"
tier = "Diamond"
modifications = [{ Enchanted = "Radiant" }]

[[opponent.cards]]
name = "Fang"
tier = "Diamond"
modifications = [{ Enchanted = "Radiant" }]

[[opponent.cards]]
name = "Fang"
tier = "Diamond"
modifications = [{ Enchanted = "Radiant" }]
