name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Nix
        uses: cachix/install-nix-action@v18
        with:
          nix_path: "nixpkgs=channel:nixos-unstable"

      - name: Enter Nix shell & build
        run: |
          nix-shell --run "cargo +nightly test --verbose"
